import sys
import os

project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '../..'))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

import unittest
from backend.app import create_app

class TestCreateTournamentAPI(unittest.TestCase):
    def setUp(self):
        self.app = create_app()
        self.app.testing = True
        self.client = self.app.test_client()

    def test_create_valid_tournament(self):
        mock_data = {
            "name": "Test Turbo Cup 2026",
            "start_date": "2026-06-01",
            "end_date": "2026-06-05"
        }

        response = self.client.post(
            '/api/tournaments/',
            json=mock_data
        )

        self.assertEqual(response.status_code, 201, f"Endpoint failure: Code {response.status_code} recieved")

        data = response.get_json()
        self.assertIn("id", data, "Response must contain the id generated by firestore")
        self.assertEqual(data["name"], "Test Turbo Cup 2026", "The almacenated name isn't the expected value")

        self.assertEqual(data["status"], "scheduled", "The future tournament should have scheduled status")

    def test_create_tournament_missing_data(self):
        bad_data = {
            "name": "Torneo Roto"
        }
        response = self.client.post('/api/tournaments/', json=bad_data)

        self.assertEqual(response.status_code, 400, "Server shouldn't accept requests without start date")

if __name__ == '__main__':
    unittest.main()